import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
    title: "Next.js Starter Boilerplate",
    description: "Generated by npx degit fabioespindula/nextjs"
};

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter" // opcional: cria uma custom property CSS
});

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>{children}</body>
        </html>
    );
}
